# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/api.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/api.proto\x12\x0fgnss_radar_math\"-\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"0\n\x16ListCoordinatesRequest\x12\x16\n\x0esatellite_name\x18\x01 \x01(\t\"K\n\x17ListCoordinatesResponse\x12\x30\n\x0b\x63oordinates\x18\n \x03(\x0b\x32\x1b.gnss_radar_math.Coordinate2w\n\x0fGnssMathService\x12\x64\n\x0fListCoordinates\x12\'.gnss_radar_math.ListCoordinatesRequest\x1a(.gnss_radar_math.ListCoordinatesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COORDINATE']._serialized_start=37
  _globals['_COORDINATE']._serialized_end=82
  _globals['_LISTCOORDINATESREQUEST']._serialized_start=84
  _globals['_LISTCOORDINATESREQUEST']._serialized_end=132
  _globals['_LISTCOORDINATESRESPONSE']._serialized_start=134
  _globals['_LISTCOORDINATESRESPONSE']._serialized_end=209
  _globals['_GNSSMATHSERVICE']._serialized_start=211
  _globals['_GNSSMATHSERVICE']._serialized_end=330
# @@protoc_insertion_point(module_scope)
